parameters:
    session.service_id: session.handler.pdo
    cookie_domain: ~
    role_hierarchy:
        ROLE_TEACHER:     ROLE_USER
        ROLE_BACKEND:     ROLE_USER
        ROLE_ADMIN:       [ROLE_TEACHER, ROLE_BACKEND]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    security_disabled_uri_prefixs:
        - anon
        - callback
        - api

    route_white_list:
        - '/crontab'
        - '/passport/notify'
        - '/oauth/v2/token'
        - '/login/oauth/access_token'
        - '/uploader/upload_callback'
        - '/uploader/process_callback'
        - '/uploadfile/upload'
        - '/disk/upload'
        - '/file/upload'
        - '/editor/upload'
        - '/disk/convert/callback'
        - '/partner/discuz/api/notify'
        - '/bddServer/callback'