services:
#    custom.example:
#        class: CustomBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    custom.activity.extension:
        class: CustomBundle\Extension\ActivityExtension
        calls:
            - [setBiz, ['@biz']]
        tags:
            - { name: extension }