services:

    course_member_event_subscriber:
        class: Biz\Course\Event\CourseMemberEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    content_event_subscriber:
        class: Biz\Content\Event\ContentEventSubscriber
        arguments: ['@biz']
        tags:
           - { name: codeages_plugin.event.subscriber }

    user_user_event_subscriber:
        class: Biz\User\Event\UserEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    task_event_subscriber:
        class: Biz\Task\Event\ActivitySubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    activity_event_subscriber:
        class: Biz\Activity\Event\ThreadSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    course_statistics_event_subscriber:
        class: Biz\Course\Event\StatisticsSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    course_set_statistics_event_subscriber:
        class: Biz\Course\Event\CourseSetStatisticsSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }
    
    course_set_teacher_event_subscriber:
        class: Biz\Course\Event\CourseSetTeacherSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    course_set_event_subscriber:
        class: Biz\Course\Event\CourseSetSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    upload_file_event_subscriber:
        class: Biz\File\Event\UploadFileEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    course_sync_event_subscriber:
        class: Biz\Course\Event\CourseSyncSubscriber
        arguments: ['@biz']
        tags: 
            - { name: codeages_plugin.event.subscriber }        

    task_sync_event_subscriber:
        class: Biz\Task\Event\TaskSyncSubscriber
        arguments: ['@biz']
        tags: 
            - { name: codeages_plugin.event.subscriber }

    testpaper_sync_event_subscriber:
        class: Biz\Testpaper\Event\TestpaperSyncSubscriber
        arguments: ['@biz']
        tags: 
            - { name: codeages_plugin.event.subscriber }

    question_sync_event_subscriber:
        class: Biz\Question\Event\QuestionSyncSubscriber
        arguments: ['@biz']
        tags: 
            - { name: codeages_plugin.event.subscriber }

    tokenbucket_event_subscriber:
        class: Biz\PostFilter\Event\TokenBucketEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    testpaper_event_subscriber:
        class: Biz\Testpaper\Event\TestpaperEventSubscriber
        arguments: ['@biz']
        tags: 
            - { name: codeages_plugin.event.subscriber }


    user_account_event_subscriber:
        class: Codeages\Biz\Pay\Subscriber\AccountSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    question_analysis_envet_subscriber:
        class: Biz\Question\Event\QuestionAnalysisEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

